name: Weather status

on:
  schedule:
    - cron: "*/60 * * * *" # Every hour

jobs:
  weather_update:
    runs-on: macOS-latest
    name: Weather
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Weather
        uses: ./
        with:
          Latitude: ${{ secrets.Latitude }}
          Longitude: ${{ secrets.Longitude }}
          DarkSkySecretKey: ${{ secrets.DarkSkySecretKey }}
          SlackAccessToken: ${{ secrets.SlackAccessToken }}
